version: '2'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    command: almanach-api --config-file /etc/almanach/almanach.conf
    depends_on:
      - messaging
      - database
    ports:
      - "80:8000"
  collector:
    build:
      context: .
      dockerfile: Dockerfile
    command: almanach-collector --config-file /etc/almanach/almanach.conf
    depends_on:
      - database
      - messaging
  messaging:
    image: rabbitmq
    ports:
      - "5672:5672"
  database:
    image: mongo
    ports:
      - "27017:27017"
  test:
    build:
      context: .
      dockerfile: Dockerfile.integration-tests
      args:
        SKIP_TOX: "true"
    environment:
      TEST_CONTAINER: "true"
    depends_on:
      - api
      - collector
      - database
      - messaging
